# Generated by Django 2.1.4 on 2018-12-16 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ModelDataBase', '0002_auto_20181212_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseaccount',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
